; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_test=music_data_test
.endif

music_data_test:
	.byte 2
	.word @instruments
	.word @samples-4
; 00 : Main Theme
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Infiltration
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_test
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env18,@env9,@env22,@env0 ; 00 : Lead
	.word @env17,@env9,@env12,@env0 ; 01 : Closed Hat
	.word @env8,@env4,@env12,@env0 ; 02 : Tri Snare
	.word @env8,@env1,@env12,@env0 ; 03 : Tri Kick
	.word @env21,@env9,@env12,@env0 ; 04 : Noise Snare
	.word @env10,@env15,@env12,@env0 ; 05 : Noise Kick
	.word @env16,@env9,@env12,@env0 ; 06 : Open Hat
	.word @env2,@env9,@env14,@env6 ; 07 : Square Bass
	.word @env20,@env9,@env3,@env5 ; 08 : Strings

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$be,$bc,$ba,$b8,$00,$04
@env2:
	.byte $00,$c6,$7f,$00,$02
@env3:
	.byte $c0,$c0,$c1,$00,$02
@env4:
	.byte $c0,$bf,$be,$bd,$bc,$00,$04
@env5:
	.byte $00,$bf,$7f,$00,$02
@env6:
	.byte $00,$c5,$7f,$00,$02
@env7:
	.byte $00,$c0,$b9,$b5,$b6,$bc,$c4,$ca,$cb,$c7,$00,$01
@env8:
	.byte $00,$cf,$7f,$00,$02
@env9:
	.byte $c0,$7f,$00,$01
@env10:
	.byte $00,$cf,$cd,$cb,$c9,$c7,$00,$05
@env11:
	.byte $00,$c0,$be,$bd,$bd,$bf,$c1,$c3,$c3,$c2,$00,$01
@env12:
	.byte $7f,$00,$00
@env13:
	.byte $00,$c0,$bc,$ba,$bb,$be,$c2,$c5,$c6,$c4,$00,$01
@env14:
	.byte $c1,$7f,$00,$00
@env15:
	.byte $ba,$c0,$00,$01
@env16:
	.byte $00,$ca,$c9,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c3,$c2,$c1,$c0,$00,$0d
@env17:
	.byte $00,$ca,$c9,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env18:
	.byte $00,$cc,$cb,$ca,$c9,$00,$04
@env19:
	.byte $00,$c0,$bf,$02,$c0,$c0,$c1,$c1,$c1,$00,$01
@env20:
	.byte $00,$c2,$c5,$c8,$ca,$04,$c8,$c5,$c2,$c0,$00,$09
@env21:
	.byte $00,$cd,$ca,$c7,$c4,$00,$04
@env22:
	.byte $c2,$c2,$c1,$00,$02

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $9f, $48, $ff, $9f, $48, $ff, $9f
@song0ref13:
	.byte $48, $00, $ff, $89, $80, $50, $c6, $20, $2c, $91, $48, $43, $20, $91, $00, $a5, $1e, $87, $20, $87, $27, $c7
@song0ref35:
	.byte $49, .lobyte(@env19), .hibyte(@env19), $81, $49, .lobyte(@env11), .hibyte(@env11), $81, $49, .lobyte(@env13), .hibyte(@env13)
	.byte $81, $48, $49, .lobyte(@env7), .hibyte(@env7), $bb, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $20, $87, $23, $87
	.byte $25, $91, $23, $91, $22, $91, $20, $91, $48, $23, $91, $00, $91, $2a, $91, $27, $db
	.byte $41, $17
	.word @song0ref35
@song0ref81:
	.byte $cd, $20, $87, $23
@song0ref85:
	.byte $87, $48, $25, $b9, $25, $87, $27, $87, $25, $91, $23, $91, $22, $91, $20, $87, $1e, $87, $48, $20, $c7, $49, .lobyte(@env19)
	.byte .hibyte(@env19), $81, $49, .lobyte(@env11), .hibyte(@env11), $81, $49, .lobyte(@env13), .hibyte(@env13), $81, $49, .lobyte(@env7)
	.byte .hibyte(@env7), $bb, $49, .lobyte(@env0), .hibyte(@env0), $4a, $43, $50, $3a, $2c, $20, $91
	.byte $41, $27
	.word @song0ref13
	.byte $41, $17
	.word @song0ref35
	.byte $41, $1d
	.word @song0ref81
@song0ref141:
	.byte $48, $00, $f5, $80, $20, $a5
@song0ref147:
	.byte $48, $2c, $9b, $27, $f9, $49, .lobyte(@env19), .hibyte(@env19), $81, $49, .lobyte(@env11), .hibyte(@env11), $81, $49
	.byte .lobyte(@env13), .hibyte(@env13), $81, $48, $49, .lobyte(@env7), .hibyte(@env7), $cf, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $80, $25, $91, $27, $91, $25, $91, $23, $91
	.byte $41, $10
	.word @song0ref147
	.byte $48, $25, $9b, $25, $eb, $25, $87, $27
	.byte $41, $19
	.word @song0ref85
	.byte $41, $14
	.word @song0ref141
	.byte $41, $10
	.word @song0ref147
	.byte $48, $25, $9b, $25, $eb, $25, $87, $27
	.byte $41, $19
	.word @song0ref85
	.byte $48, $00, $ff, $9d, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref221:
	.byte $8e
@song0ref222:
	.byte $08, $8f, $00, $08, $8f, $00, $93
@song0ref229:
	.byte $08, $8f, $00, $93, $08, $8f, $00, $06, $8f, $00, $07, $8f, $00
	.byte $41, $14
	.word @song0ref222
	.byte $41, $14
	.word @song0ref222
	.byte $41, $14
	.word @song0ref222
	.byte $41, $14
	.word @song0ref222
	.byte $41, $11
	.word @song0ref222
@song0ref257:
	.byte $0b, $8f, $00, $0f, $8f, $00, $0f, $8f, $00, $93
@song0ref267:
	.byte $0f, $8f, $00, $93, $0f, $8f, $00, $0d, $8f, $00
	.byte $41, $14
	.word @song0ref257
@song0ref280:
	.byte $0b
@song0ref281:
	.byte $8f, $00, $0d, $8f, $00, $0d, $8f, $00, $93, $0d, $8f, $00, $93, $0d, $8f, $00, $0d, $8f, $00, $0f
	.byte $41, $10
	.word @song0ref281
	.byte $0b, $8f, $00, $0a, $8f, $00
	.byte $41, $14
	.word @song0ref222
	.byte $41, $14
	.word @song0ref222
	.byte $41, $0a
	.word @song0ref222
	.byte $80, $23, $c7, $49, .lobyte(@env19), .hibyte(@env19), $81, $49, .lobyte(@env11), .hibyte(@env11), $81, $49, .lobyte(@env13)
	.byte .hibyte(@env13), $81, $49, .lobyte(@env7), .hibyte(@env7), $bb, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e
	.byte $41, $0a
	.word @song0ref229
	.byte $41, $0a
	.word @song0ref257
	.byte $80, $23, $db, $49, .lobyte(@env19), .hibyte(@env19), $81, $49, .lobyte(@env11), .hibyte(@env11), $81, $49, .lobyte(@env13)
	.byte .hibyte(@env13), $81, $49, .lobyte(@env7), .hibyte(@env7), $bb, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8e
	.byte $41, $0a
	.word @song0ref267
	.byte $41, $0a
	.word @song0ref280
	.byte $80, $23, $cd, $8e, $0f
	.byte $41, $10
	.word @song0ref281
@song0ref387:
	.byte $0b, $8f, $00, $0a, $8f, $00, $80, $1b, $c7, $49, .lobyte(@env19), .hibyte(@env19), $81, $49, .lobyte(@env11), .hibyte(@env11)
	.byte $81, $49, .lobyte(@env13), .hibyte(@env13), $81, $49, .lobyte(@env7), .hibyte(@env7), $a7, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $93, $43, $50, $4d, $27, $1b, $91
	.byte $41, $14
	.word @song0ref221
	.byte $41, $14
	.word @song0ref222
	.byte $41, $11
	.word @song0ref222
	.byte $41, $14
	.word @song0ref257
	.byte $41, $14
	.word @song0ref257
	.byte $41, $15
	.word @song0ref280
	.byte $41, $10
	.word @song0ref281
	.byte $0b, $8f, $00, $0a, $8f, $00
	.byte $41, $14
	.word @song0ref222
	.byte $41, $14
	.word @song0ref222
@song0ref456:
	.byte $80, $27, $9b, $23, $f9, $49, .lobyte(@env19), .hibyte(@env19), $81, $49, .lobyte(@env11), .hibyte(@env11), $81, $49
	.byte .lobyte(@env13), .hibyte(@env13), $81, $49, .lobyte(@env7), .hibyte(@env7), $cf, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $00, $91, $8e, $08, $8f, $00, $06, $8f, $00, $0b, $8f, $00
	.byte $41, $0a
	.word @song0ref456
	.byte $8e, $0f, $8f, $00, $0d, $8f, $00
	.byte $41, $15
	.word @song0ref280
	.byte $41, $10
	.word @song0ref281
	.byte $41, $0f
	.word @song0ref387
	.byte $41, $14
	.word @song0ref221
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
@song0ref519:
	.byte $86, $1d, $87, $80, $14, $85, $00, $14, $8f, $00, $84, $22, $87, $00, $87, $80, $14, $87, $84, $22, $87, $00, $91, $86
	.byte $1d, $87, $80, $14, $85, $00, $84, $22, $87, $00, $81, $80, $12, $81, $00, $13, $8f, $00
	.byte $41, $1e
	.word @song0ref519
	.byte $86, $1d, $87, $80, $13, $85, $00
	.byte $41, $21
	.word @song0ref519
	.byte $41, $1e
	.word @song0ref519
	.byte $86, $1d, $87, $80, $13, $85, $00
	.byte $41, $21
	.word @song0ref519
	.byte $41, $1e
	.word @song0ref519
@song0ref590:
	.byte $86, $1d, $87, $80, $17, $85
@song0ref596:
	.byte $00, $86, $1d, $87, $80, $1b, $85, $00, $1b, $8f, $00, $84, $22, $87, $00, $87, $80, $1b, $87, $84, $22, $87, $00, $91
	.byte $86, $1d, $87, $80, $1b
@song0ref625:
	.byte $85, $00, $84, $22, $87, $00, $81, $80, $19, $81, $00, $17, $8f
	.byte $41, $1f
	.word @song0ref596
@song0ref641:
	.byte $86, $1d, $87, $80, $17, $85
@song0ref647:
	.byte $00, $86, $1d, $87, $80, $19, $85, $00, $19, $8f, $00, $84, $22, $87, $00, $87, $80, $19, $87, $84, $22, $87, $00, $91
	.byte $86, $1d, $87, $80, $19
	.byte $41, $09
	.word @song0ref625
	.byte $1b, $8f
	.byte $41, $16
	.word @song0ref647
@song0ref684:
	.byte $85, $00, $84, $22, $87, $00, $81, $80, $17, $81, $00, $86, $1d, $87, $80, $16, $85, $00
	.byte $41, $21
	.word @song0ref519
	.byte $41, $1e
	.word @song0ref519
	.byte $86, $1d, $87, $80, $13, $85, $00
	.byte $41, $21
	.word @song0ref519
	.byte $41, $1e
	.word @song0ref519
	.byte $41, $25
	.word @song0ref590
	.byte $41, $1f
	.word @song0ref596
	.byte $41, $1a
	.word @song0ref641
	.byte $41, $09
	.word @song0ref625
	.byte $1b, $8f
	.byte $41, $16
	.word @song0ref647
	.byte $41, $0e
	.word @song0ref684
	.byte $41, $21
	.word @song0ref519
	.byte $41, $1e
	.word @song0ref519
	.byte $86, $1d, $87, $80, $13, $85, $00
	.byte $41, $21
	.word @song0ref519
	.byte $41, $1e
	.word @song0ref519
	.byte $41, $25
	.word @song0ref590
	.byte $41, $1f
	.word @song0ref596
	.byte $41, $1a
	.word @song0ref641
	.byte $41, $09
	.word @song0ref625
	.byte $1b, $8f
	.byte $41, $16
	.word @song0ref647
	.byte $41, $0e
	.word @song0ref684
	.byte $41, $21
	.word @song0ref519
	.byte $41, $1e
	.word @song0ref519
	.byte $86, $1d, $87, $80, $13, $85, $00
	.byte $41, $21
	.word @song0ref519
	.byte $41, $1e
	.word @song0ref519
	.byte $41, $25
	.word @song0ref590
	.byte $41, $1f
	.word @song0ref596
	.byte $41, $1a
	.word @song0ref641
	.byte $41, $09
	.word @song0ref625
	.byte $1b, $8f
	.byte $41, $16
	.word @song0ref647
	.byte $41, $0e
	.word @song0ref684
	.byte $41, $21
	.word @song0ref519
	.byte $41, $1e
	.word @song0ref519
	.byte $86, $1d, $87, $80, $13, $85, $00, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref836:
	.byte $8a
@song0ref837:
	.byte $22, $87, $00, $87, $82, $20, $8b, $00, $83, $88, $1b, $8b, $00, $83, $82, $20, $87, $88, $1b, $8b, $00, $83, $82, $20
	.byte $87, $8a, $22, $87, $00, $87, $88, $1b, $8b, $00, $83, $8c, $22, $91
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87
	.byte $41, $1e
	.word @song0ref837
	.byte $41, $1c
	.word @song0ref836
	.byte $8a, $22, $87, $00, $87, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref1074:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $41, $0a
	.word @song0ref1074
	.byte $41, $0a
	.word @song0ref1074
	.byte $41, $0a
	.word @song0ref1074
	.byte $41, $0a
	.word @song0ref1074
	.byte $41, $0a
	.word @song0ref1074
	.byte $41, $0a
	.word @song0ref1074
	.byte $ff, $9f, $42
	.word @song0ch4loop
@song1ch0:
	.byte $ff, $ff, $9f, $48, $ff, $ff, $9f, $48, $ff, $ff, $9f, $48, $ff, $ff, $9f
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80
@song1ref21:
	.byte $14, $8f, $17, $8f, $1b, $8f, $00, $8f, $1a, $ff, $8d, $00, $c5, $48, $1b, $a1, $1a, $8f, $00, $ff, $e7, $48
	.byte $41, $0d
	.word @song1ref21
	.byte $48, $20, $a1, $1e, $8f, $00, $d7, $20, $8f, $00, $8f, $1e, $8f, $20, $8f, $00, $8f, $1e, $8f, $20, $8f, $00, $8f, $48
	.byte $41, $14
	.word @song1ref21
	.byte $48
	.byte $41, $0d
	.word @song1ref21
	.byte $48, $20, $a1, $1e, $8f, $00, $d7, $20, $b3, $00, $8f
@song1ref88:
	.byte $1b, $b3, $19, $8f, $48, $20, $c5, $1b, $c5, $1a, $c5, $17, $c5, $48, $14, $c5, $0f, $c5, $0e, $a1, $00, $a1
	.byte $41, $0d
	.word @song1ref88
	.byte $ff, $d5, $00, $c5, $42
	.word @song1ch0loop
@song1ch1:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $90
@song1ref127:
	.byte $20, $93, $00, $9d, $20, $8f, $23, $93, $00, $8b, $20, $93, $00, $9d, $20, $8f, $20, $93, $00, $8b, $23, $93, $00, $8b
	.byte $25, $93, $00, $8b, $28, $93, $00, $9d, $28, $8f, $28, $93, $00, $8b, $28, $93, $00, $9d, $28, $8f, $28, $93, $00, $8b
	.byte $27, $93, $00, $8b, $27, $93, $00, $8b
@song1ch1loop:
	.byte $41, $1c
	.word @song1ref127
	.byte $41, $14
	.word @song1ref127
	.byte $28, $93, $00, $8b, $25, $93, $00, $8b
	.byte $41, $38
	.word @song1ref127
	.byte $41, $1c
	.word @song1ref127
	.byte $41, $14
	.word @song1ref127
	.byte $28, $93, $00, $8b, $25, $93, $00, $8b
	.byte $41, $38
	.word @song1ref127
@song1ref218:
	.byte $2c, $8f, $27, $8f, $26, $8f, $27, $8f, $2c, $8f, $27, $8f, $26, $8f, $27, $8f, $2c, $8f, $27, $8f, $23, $8f, $27, $8f
	.byte $2c, $8f, $27, $8f, $23, $8f, $27, $8f, $2c, $8f, $27, $8f, $20, $8f, $27, $8f, $2c, $8f, $27, $8f, $20, $8f, $27, $8f
	.byte $2c, $8f, $27, $8f, $00, $e9
	.byte $41, $36
	.word @song1ref218
	.byte $42
	.word @song1ch1loop
@song1ch2:
@song1ref278:
	.byte $80
@song1ref279:
	.byte $12, $8d, $00, $14, $8d, $00, $91, $12, $8d, $00, $14, $8d, $00, $91
	.byte $41, $0e
	.word @song1ref279
@song1ref296:
	.byte $17, $9f, $00, $16, $8d, $00, $91, $0d, $8d, $00, $0f, $8d, $00, $91, $0d, $8d, $00, $0f, $8d, $00, $91, $0d, $8d, $00
	.byte $0f, $8d, $00, $84, $22, $87, $00, $85, $22, $87, $80, $0d, $83, $00, $0f, $8d, $00, $91, $84, $22, $87, $00, $85, $22
	.byte $87, $00, $a9
	.byte $41, $0e
	.word @song1ref278
	.byte $41, $0e
	.word @song1ref279
	.byte $41, $18
	.word @song1ref296
	.byte $86, $1d, $87, $80, $0f, $83, $00, $84, $22, $87, $00, $85, $22, $87, $80, $0d, $83, $00, $86, $1d, $87, $80, $0f, $83
	.byte $00, $84, $22, $87, $00, $85, $22, $87, $00, $85, $86, $1d, $87, $00, $85, $84, $22, $87, $00, $85, $22, $87, $00, $85
@song1ch2loop:
@song1ref405:
	.byte $86, $1d, $87, $80, $12, $83, $00, $14, $8d, $00, $91, $12, $8d, $00, $84, $22, $87, $80, $14, $83, $00, $91, $86, $1d
	.byte $87, $80, $12, $83, $00, $86, $1d, $87, $80, $14, $83, $00, $91, $86, $1d, $87, $80, $12, $83, $00, $86, $1d, $87, $80
	.byte $14, $83, $00, $91, $84, $22, $87, $80, $17, $95, $00, $16, $8d, $00, $91, $86, $1d, $87, $80, $0d, $83, $00, $0f, $8d
	.byte $00, $91, $0d, $8d, $00, $84, $22, $87, $80, $0f, $83, $00, $91, $86, $1d, $87, $80, $0d, $83, $00, $86, $1d, $87, $80
	.byte $0f, $83, $00, $91, $86, $1d, $87, $80, $0d, $83, $00, $86, $1d, $87, $80, $0f, $83, $00, $91, $84, $22, $87, $00, $bb
	.byte $41, $5d
	.word @song1ref405
	.byte $41, $5d
	.word @song1ref405
	.byte $41, $5d
	.word @song1ref405
@song1ref534:
	.byte $22, $87, $80, $08, $83, $00, $91, $14, $8d, $00, $84, $22, $87, $80, $08, $83, $00, $84, $22, $87, $80, $03, $83, $00
	.byte $91, $0f, $8d, $00, $84, $22, $87, $80, $03, $83, $00, $84, $22, $87, $80, $02, $83, $00, $91, $0e, $8d, $00, $84, $22
	.byte $87, $80, $02, $83, $00, $84, $22, $87, $80, $0b, $83, $00, $91, $17, $8d, $00, $84, $22, $87, $80, $0b, $83, $00, $84
	.byte $41, $1f
	.word @song1ref534
	.byte $95, $00, $eb, $84
	.byte $41, $38
	.word @song1ref534
	.byte $84, $22, $87, $80, $08, $83, $00, $91, $14, $8d, $00, $84, $22, $87, $80, $08, $85, $84, $22, $87, $80, $08, $83, $00
	.byte $08, $8d, $00, $91, $84, $22, $87, $00, $85, $22, $87, $80, $08, $83, $00, $91, $14, $8d, $00, $08, $9f, $00, $b5, $42
	.word @song1ch2loop
@song1ch3:
	.byte $ff, $ff, $9f, $ff, $8f, $88
@song1ref672:
	.byte $1b, $8b, $00, $81, $1b, $8b, $00, $a5, $1b, $8b, $00, $81, $1b, $8b, $00, $a5, $ff, $ff, $9f, $fd, $8a, $22, $87, $00
	.byte $85, $88, $1b, $8b, $00, $81, $1b, $8b, $00, $81, $8a, $22, $87, $00, $85, $88, $1b, $8b, $00, $81, $1b, $8b, $00, $81
	.byte $8a, $22, $87, $00, $85, $88, $1b, $8b, $00, $81, $1b, $8b, $00, $81
@song1ch3loop:
@song1ref735:
	.byte $8a, $22, $87, $00, $85, $82, $20, $8b, $00, $81, $20, $8b, $00, $93, $88, $1b, $8b, $00, $81, $82, $20, $8b, $00, $81
	.byte $8a, $22, $87, $00, $85, $22, $87, $00, $85, $82, $20, $8b, $00, $81, $8a, $22, $87, $00, $85, $22, $87, $00, $85, $82
	.byte $20, $8b, $00, $81, $88, $1b, $8b, $00, $81, $82, $20, $8b, $00, $81, $8c, $22, $8f, $82, $20, $8b, $00, $81
	.byte $41, $3a
	.word @song1ref735
	.byte $41, $3a
	.word @song1ref735
	.byte $41, $3a
	.word @song1ref735
	.byte $41, $3a
	.word @song1ref735
	.byte $41, $3a
	.word @song1ref735
	.byte $41, $3a
	.word @song1ref735
	.byte $41, $3a
	.word @song1ref735
	.byte $88, $1b, $8b, $00, $a5
	.byte $41, $10
	.word @song1ref672
	.byte $41, $10
	.word @song1ref672
	.byte $41, $0f
	.word @song1ref672
	.byte $ff, $1b, $8b, $00, $a5
	.byte $41, $10
	.word @song1ref672
	.byte $41, $10
	.word @song1ref672
	.byte $41, $0f
	.word @song1ref672
	.byte $ff, $42
	.word @song1ch3loop
@song1ch4:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
@song1ch4loop:
@song1ref871:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
	.byte $41, $0f
	.word @song1ref871
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $42
	.word @song1ch4loop
