; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses release notes, you must set FAMISTUDIO_USE_RELEASE_NOTES = 1.
; Arpeggios are used, you must set FAMISTUDIO_USE_ARPEGGIO = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : World 1 - Light
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env19,@env10,@env13,@env0 ; 00 : Noise Snare
	.word @env8,@env10,@env13,@env0 ; 01 : Triangle Bass
	.word @env16,@env10,@env13,@env0 ; 02 : Closed Hat
	.word @env11,@env15,@env13,@env0 ; 03 : Noise Kick
	.word @env8,@env3,@env13,@env0 ; 04 : Tri Kick
	.word @env8,@env5,@env13,@env0 ; 05 : Tri Snare
	.word @env7,@env10,@env14,@env0 ; 06 : Arp 2, Crescendo
	.word @env8,@env10,@env13,@env6 ; 07 : Square
	.word @env4,@env10,@env14,@env0 ; 08 : Arp 2, Decrescendo
	.word @env8,@env10,@env13,@env12 ; 09 : Square, more vibrato
	.word @env8,@env10,@env13,@env2 ; 0a : Square 1, slight detune
	.word @env8,@env10,@env13,@env1 ; 0b : Square, slight detune more vibrato
	.word @env9,@env10,@env13,@env0 ; 0c : Arp 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$be,$c5,$cc,$c5,$be,$b6,$b2,$b7,$00,$01
@env2:
	.byte $00,$be,$c1,$be,$ba,$bf,$c3,$be,$ba,$00,$01
@env3:
	.byte $c0,$be,$bc,$ba,$b8,$00,$04
@env4:
	.byte $06,$cb,$02,$cb,$00,$03,$cb,$08,$ca,$05,$c9,$05,$c8,$05,$c7,$06,$c6,$07,$c5,$04,$c4,$02,$c3,$05,$c2,$06,$c1,$08,$c0,$0a,$c0,$00,$1e
@env5:
	.byte $c0,$bf,$be,$bd,$bc,$00,$04
@env6:
	.byte $00,$c0,$c3,$c0,$bc,$c1,$c5,$c0,$bc,$00,$01
@env7:
	.byte $06,$c0,$02,$c1,$00,$03,$c1,$05,$c2,$05,$c3,$04,$c4,$05,$c5,$08,$c6,$0a,$c7,$04,$c8,$04,$c9,$08,$ca,$04,$cb,$08,$cc,$06,$ce,$00,$1e
@env8:
	.byte $00,$cf,$7f,$00,$02
@env9:
	.byte $06,$cd,$02,$cd,$00,$03,$cd,$03,$cc,$04,$cb,$04,$ca,$03,$c9,$03,$c8,$03,$c7,$03,$c6,$03,$c5,$03,$c4,$03,$c3,$03,$c2,$03,$c1,$02,$c1,$00,$20
@env10:
	.byte $c0,$7f,$00,$01
@env11:
	.byte $00,$cf,$cd,$cb,$c9,$c7,$00,$05
@env12:
	.byte $00,$c0,$c7,$ce,$c7,$c0,$b8,$b2,$b9,$00,$01
@env13:
	.byte $7f,$00,$00
@env14:
	.byte $c2,$7f,$00,$00
@env15:
	.byte $ba,$c0,$00,$01
@env16:
	.byte $00,$ca,$c9,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env17:
	.byte $c0,$c3,$c5,$c8,$00,$00
@env18:
	.byte $c0,$c3,$c8,$00,$00
@env19:
	.byte $00,$cd,$ca,$c7,$c4,$00,$04
@env20:
	.byte $c0,$c2,$c5,$c9,$00,$00
@env21:
	.byte $c0,$c5,$c9,$00,$00
@env22:
	.byte $c0,$c5,$ca,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $4c, $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $4b, .lobyte(@env18), .hibyte(@env18), $98
@song0ref10:
	.byte $2b, $af, $45, $e1, $00, $a7, $48, $81, $4b, .lobyte(@env22), .hibyte(@env22), $29, $a9, $45, $e1, $00, $ab, $48, $4b
	.byte .lobyte(@env18), .hibyte(@env18), $2b, $ad, $45, $dd, $00, $97, $4b, .lobyte(@env21), .hibyte(@env21), $2a, $8b, $45
	.byte $85, $48, $bb, $00, $a3, $4d, $2c, $91, $45, $c5, $00, $48, $4b, .lobyte(@env18), .hibyte(@env18)
	.byte $41, $1f
	.word @song0ref10
	.byte $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $b3, $4b, .lobyte(@env10), .hibyte(@env10), $4c, $94, $19, $83, $00, $83, $48
	.byte $1b, $93, $00, $1b, $85, $00, $8d, $19, $85, $00, $8d, $17, $8f, $00, $9b, $19, $91, $00, $b1, $48, $af, $13, $83, $00
	.byte $8f, $16, $99, $00, $91, $1b, $a9, $00, $81, $1b, $85, $00, $8d, $48, $1f, $ad, $00, $95, $22, $95, $00, $95, $26, $8d
	.byte $00, $85, $22, $85, $00, $8d, $1f, $89, $1d, $85, $00, $81, $48, $1b, $ad, $00, $95, $96, $16, $f5, $48, $af, $00, $ff
	.byte $8d, $48, $eb, $94, $1b, $87, $00, $23, $81, $00, $85, $27, $81, $00, $85, $2a, $83, $00, $83, $27, $81, $00, $85, $23
	.byte $81, $00, $85, $17, $81, $00, $85, $48, $bb, $1d, $85, $00, $81, $25, $81, $00, $85, $29, $81, $00, $85, $2c, $85, $00
	.byte $81, $29, $81, $00, $85, $25, $81, $00, $85, $20, $81, $00, $85, $29, $85, $00, $81, $25, $81, $00, $85, $20, $81, $00
	.byte $85, $1d, $81, $00, $85, $48, $97, $14, $85, $00, $81, $1b
@song0ref236:
	.byte $81, $00, $85, $1f, $81, $00, $85, $22, $81, $00, $85, $24, $81, $00, $85, $27, $81, $00, $85, $24
	.byte $41, $0b
	.word @song0ref236
	.byte $27, $81, $00, $85, $29, $81, $00, $85, $2b, $81, $00, $85, $2e, $81, $00, $85, $30, $81, $00, $85, $48
@song0ref280:
	.byte $33, $81, $2b, $81, $2e, $81, $30, $81, $33, $81, $2b, $81, $2e, $81, $30, $81
	.byte $41, $10
	.word @song0ref280
	.byte $41, $10
	.word @song0ref280
	.byte $33, $00, $87
@song0ref305:
	.byte $1d, $83, $00, $83, $1e, $87, $00, $1d, $85, $00, $81, $1b, $87, $00, $19, $85, $00, $81, $17, $85, $00, $81, $16, $85
	.byte $00, $81, $48, $14, $ad, $00, $95, $1b, $f5, $48, $97, $00, $95, $1d, $ad, $19, $ad, $00, $ad, $48, $1b, $ad, $00, $95
	.byte $1b, $89, $00, $89, $96, $1b, $dd, $48, $ff, $8f, $00, $ad
@song0ref365:
	.byte $48, $4b, .lobyte(@env17), .hibyte(@env17), $8c, $16, $a7, $45, $ff, $93, $48, $4b, .lobyte(@env18), .hibyte(@env18)
	.byte $90, $18, $af, $45, $ff, $89, $00, $48, $4b, .lobyte(@env20), .hibyte(@env20), $8c, $19, $ad, $45, $ff, $8d, $48, $4b
	.byte .lobyte(@env21), .hibyte(@env21), $90, $1b, $ab, $45, $ff, $8f
	.byte $41, $0b
	.word @song0ref365
	.byte $48, $4b, .lobyte(@env17), .hibyte(@env17), $8c, $16, $a7, $45, $ff, $93, $48, $4b, .lobyte(@env20), .hibyte(@env20)
	.byte $90, $19, $85, $45, $d5, $4d, $14, $83, $45, $d7
	.byte $41, $10
	.word @song0ref365
	.byte $48, $00, $ff, $bd
@song0ref440:
	.byte $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf
	.byte $41, $0a
	.word @song0ref440
	.byte $41, $0a
	.word @song0ref440
	.byte $41, $0a
	.word @song0ref440
	.byte $41, $0a
	.word @song0ref440
	.byte $48, $ff, $bf, $48, $ff, $bf, $48, $ff, $bf, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref480:
	.byte $ff
@song0ref481:
	.byte $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $91, $8e, $16, $ab
@song0ref499:
	.byte $1b, $95, $13, $85, $00, $8d, $16, $83, $00, $8f, $1b, $9b, $00, $8f, $1d, $a7, $00, $83, $1f, $85, $00, $8d, $22, $bb
	.byte $00, $87, $1f, $9d, $00, $8d, $1d, $9f, $00, $8b, $1f, $89, $00, $89, $92, $1b, $ff, $8b, $00, $97, $8e, $1b, $87, $00
	.byte $1d, $87, $00, $1e, $93, $00, $1e, $83, $00, $8f, $1d, $85, $00, $8d, $1b, $93, $00, $97, $1d, $91, $00, $8d, $16, $89
	.byte $19, $83, $00, $83, $1a, $85, $00, $81
	.byte $41, $17
	.word @song0ref499
	.byte $ad, $00, $95, $26, $95, $00, $95, $29, $8d, $00, $85, $26, $85, $00, $8d, $22, $89, $20, $83, $00, $83, $1f, $ab, $00
	.byte $97, $92, $1b, $f5, $af, $00, $dd, $8e, $16, $ad, $17, $ad, $00, $95, $1e, $f5, $97, $00, $91, $92, $1f, $81, $8e, $20
	.byte $ad, $1d, $bd, $00, $85, $19, $89, $00, $89, $18, $b7, $00, $8d, $92, $1f, $f3, $c3, $00, $a5, $8e, $20, $83, $00, $83
	.byte $22, $87, $00, $20, $85, $00, $81, $1e, $87, $00, $1d, $85, $00, $81, $1b, $85, $00, $81, $19, $85, $00, $81, $17, $ad
	.byte $00, $95, $1e, $f5, $97, $00, $91, $1f, $81, $20, $ad, $1d, $ad, $19, $a1, $00, $89, $20, $b1, $00, $91, $1f, $87, $00
	.byte $8b, $92, $1f, $dd, $ff, $8d, $00, $16, $15, $14, $13, $12, $11, $10, $0f, $0e, $0d, $0c, $0b, $0a, $09, $08, $07, $06
	.byte $05, $04, $03, $02, $01, $40, $0c, $40, $0b, $8e
@song0ref736:
	.byte $03, $9d
@song0ref738:
	.byte $00, $81, $03, $85, $00, $99, $0f, $91, $00, $99, $03, $89, $00, $95, $0a, $8f, $00, $83, $40, $0a, $83, $00, $83
	.byte $41, $18
	.word @song0ref736
	.byte $41, $18
	.word @song0ref736
	.byte $41, $0b
	.word @song0ref736
	.byte $8d, $16, $83, $00, $83, $19, $87, $00
	.byte $41, $0c
	.word @song0ref305
	.byte $85, $00, $81, $19
@song0ref785:
	.byte $85, $00, $81, $1b, $8b, $16, $12, $0f, $0d, $0a, $06, $03, $01, $40, $0a
	.byte $41, $16
	.word @song0ref738
	.byte $41, $18
	.word @song0ref736
	.byte $41, $18
	.word @song0ref736
	.byte $41, $0b
	.word @song0ref736
	.byte $8d, $14, $89, $12, $85, $00, $81, $14, $85, $00, $81, $16, $89, $18, $85, $00, $81, $19, $85, $00, $81, $1d
	.byte $41, $0e
	.word @song0ref785
	.byte $41, $16
	.word @song0ref738
	.byte $41, $18
	.word @song0ref736
	.byte $41, $18
	.word @song0ref736
	.byte $41, $0f
	.word @song0ref480
	.byte $41, $0e
	.word @song0ref481
	.byte $41, $0e
	.word @song0ref481
	.byte $41, $0e
	.word @song0ref481
	.byte $bf, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
@song0ref863:
	.byte $88
@song0ref864:
	.byte $1d
@song0ref865:
	.byte $85, $82, $0f, $91, $00, $85, $0f, $85, $00, $81, $8a, $1b, $85, $00, $8d, $82, $1b, $97, $00, $93, $0f, $89, $88, $1d
	.byte $87, $00, $8a, $1b, $85, $00, $81, $82, $16, $8f, $00, $83, $0a, $83, $00, $83, $88, $1d, $87, $82, $0f, $8f, $00, $8f
	.byte $0f, $88, $1d, $87, $00, $8b, $8a, $1b, $87, $82, $1b, $8b, $00, $89, $0f, $00, $87, $0f, $89, $00, $89, $8a, $1b, $87
	.byte $00, $88, $1d, $82, $16, $87, $0b, $00, $93, $88, $1d, $85, $82, $0f, $91, $00, $85, $0f, $89, $8a, $1b, $85, $00, $8d
	.byte $82, $1b, $95, $00, $95, $0f, $89, $88, $1d, $87, $00, $8a, $1b, $87, $00, $82, $16, $00, $87, $0b, $93, $00, $88, $1d
	.byte $87, $00, $8b, $82, $0b, $89, $06, $89, $88, $1d, $82, $0b, $87, $12, $89, $8a, $1b, $82, $0b, $87, $06, $89, $0d, $89
	.byte $08, $89, $0d, $89, $0f, $89, $8a, $1b, $82, $11, $87, $88, $1d, $82, $14, $87, $8a, $1b, $82, $0d, $83, $00, $81, $8a
	.byte $1b, $00, $87
	.byte $41, $8a
	.word @song0ref863
	.byte $41, $24
	.word @song0ref863
@song0ref1042:
	.byte $85, $82, $13, $91, $00, $85, $13, $89, $8a, $1b, $85, $00, $8d, $82, $1b, $95, $00, $95, $13, $89, $88, $1d, $87, $00
	.byte $8a, $1b, $87, $00, $82, $16, $95, $1a, $89
@song0ref1075:
	.byte $88, $1d, $85, $82, $14, $91, $00, $85, $14, $89, $8a, $1b, $85, $00, $8d, $82, $20, $95, $00, $95, $14, $89, $88, $1d
	.byte $87, $00, $8b, $82, $1b, $85, $00, $81, $14, $87, $00, $16, $87, $00, $88, $1d, $82, $17, $87, $12, $85, $00, $81, $17
	.byte $85, $00, $81, $1e, $83, $00, $83, $8a, $1b, $82, $17, $83, $00, $81, $18, $83, $00, $83, $19, $8f, $00, $9b, $19, $87
	.byte $00, $88, $1d, $87, $00, $8a, $1b, $87, $00, $82, $16, $95, $00, $89
	.byte $41, $24
	.word @song0ref863
	.byte $41, $1d
	.word @song0ref1042
	.byte $82, $18, $85, $00, $91, $18, $85, $00, $81, $8a, $1b, $85, $00, $8d, $82, $1f, $95, $00, $89, $13, $83, $00, $83, $13
	.byte $89, $88, $1d, $85, $00, $81, $8a, $1b, $85, $82, $13, $81, $1b, $8f, $00, $83, $16, $89, $88, $1d, $85, $82, $14, $85
	.byte $00, $91, $14, $85, $00, $81, $8a, $1b, $85, $00, $81, $82, $1b, $83, $00, $83, $1b, $89, $14, $85, $00, $81, $16, $89
	.byte $11, $85, $00, $81, $16, $85, $00, $81, $1d, $83, $00, $83, $16, $89, $0a, $83, $00, $83, $88, $1d, $85, $82, $1d, $81
	.byte $88, $1d, $85, $82, $16, $81, $88, $1d, $85, $82, $17, $91, $00, $85, $1e, $89, $8a, $1b, $85, $00, $8d, $82, $17, $95
	.byte $00, $95, $17, $89, $88, $1d, $87, $00, $8a, $1b, $87, $00, $82, $12, $95, $17, $83, $00, $83, $88, $1d, $85, $82, $19
	.byte $91, $00, $85, $20, $89, $8a, $1b, $85, $00, $8d, $82, $19, $95, $00, $95, $19, $89, $88, $1d, $87, $00, $8a, $1b, $87
	.byte $00, $82, $16, $95, $13, $83, $00, $83
	.byte $41, $15
	.word @song0ref1075
	.byte $8a, $1b, $87, $00, $82, $1b, $95, $0f, $83, $00, $83
	.byte $41, $15
	.word @song0ref1075
	.byte $8a, $1b, $85, $82, $16, $81, $1d, $83, $00, $83, $16, $8d, $00, $85, $88, $1d, $85, $82, $10, $91, $00, $85, $10, $89
	.byte $8a, $1b, $85, $00, $8d, $82, $1c, $95, $00, $95, $10, $89, $88, $1d, $87, $00, $8a, $1b, $87, $00, $82, $14, $95, $0f
	.byte $83, $00, $83, $88, $1d, $85, $82, $0d, $91, $00, $85, $0d, $89, $8a, $1b, $85, $00, $8d, $82, $19, $95, $00, $95, $0d
	.byte $89, $88, $1d, $87, $00, $8a, $1b, $87, $00, $82, $14, $95, $0d, $81, $00, $85
	.byte $41, $24
	.word @song0ref863
@song0ref1451:
	.byte $85, $82, $0f, $91, $00, $85, $8a, $1b, $85, $00, $99, $88, $1d, $85, $82, $1b, $8d, $00, $89, $88, $1d, $85, $00, $81
	.byte $82, $0f, $89, $88, $1d, $87, $00, $8b, $8a, $1b, $85, $82, $16, $81, $8a, $1b, $85, $82, $16, $81, $88, $1d, $85, $00
	.byte $81
	.byte $41, $24
	.word @song0ref864
	.byte $41, $23
	.word @song0ref865
	.byte $41, $23
	.word @song0ref865
	.byte $41, $10
	.word @song0ref865
	.byte $87, $16, $83, $00, $83, $19, $87, $00, $88, $1d, $87, $00, $8a, $1b, $85, $00, $81, $82, $0a, $a1
	.byte $41, $24
	.word @song0ref863
	.byte $41, $23
	.word @song0ref865
	.byte $41, $23
	.word @song0ref865
	.byte $41, $13
	.word @song0ref1451
	.byte $82, $12, $85, $00, $81, $88, $1d, $87, $00, $82, $0a, $89, $8a, $1b, $85, $82, $0a, $81, $8a, $1b, $85, $82, $0a, $81
	.byte $88, $1d, $85, $82, $0a, $81
	.byte $41, $24
	.word @song0ref863
	.byte $41, $23
	.word @song0ref865
	.byte $41, $22
	.word @song0ref865
	.byte $41, $0f
	.word @song0ref480
	.byte $41, $0e
	.word @song0ref481
	.byte $41, $0e
	.word @song0ref481
	.byte $41, $0e
	.word @song0ref481
	.byte $bf, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref1600:
	.byte $86
@song0ref1601:
	.byte $22
@song0ref1602:
	.byte $85, $00, $81, $84, $23, $00, $87, $23, $00, $87, $86, $22, $00, $87, $80, $1b, $8b, $00, $87, $84, $23, $00, $87, $23
	.byte $00, $93, $23, $00, $81, $23, $00, $81, $80, $1b, $00, $87, $86, $22, $00, $87, $80, $1b, $89, $84, $23, $00, $87, $23
	.byte $00, $87, $80, $1b, $00, $87, $86, $22, $87, $00, $80, $1b, $00, $87, $84, $23, $00, $87, $80, $1b, $00, $87, $86, $22
	.byte $83, $00, $83, $84, $23, $00, $87, $80, $1b, $89, $84, $23, $83, $00, $83, $23, $00, $87, $23, $00, $81, $23, $00, $81
	.byte $80, $1b, $00, $87, $1c, $00, $87, $1b, $87, $00, $86, $22, $83, $00, $83, $84, $23, $00, $87, $86, $22, $00, $87
	.byte $41, $59
	.word @song0ref1601
@song0ref1724:
	.byte $1b, $00, $81, $1b, $00, $81, $1b, $00, $87, $1b, $87, $00
	.byte $41, $63
	.word @song0ref1600
	.byte $41, $59
	.word @song0ref1601
	.byte $41, $0c
	.word @song0ref1724
	.byte $41, $63
	.word @song0ref1600
	.byte $41, $59
	.word @song0ref1601
	.byte $41, $0c
	.word @song0ref1724
	.byte $41, $63
	.word @song0ref1600
	.byte $41, $57
	.word @song0ref1601
@song0ref1760:
	.byte $00, $81, $1b, $00, $81, $1b, $85, $00, $81, $1b, $85, $00, $81, $86, $22, $85, $00, $81
	.byte $41, $63
	.word @song0ref1601
	.byte $41, $59
	.word @song0ref1601
	.byte $41, $0c
	.word @song0ref1724
	.byte $41, $63
	.word @song0ref1600
	.byte $41, $38
	.word @song0ref1601
	.byte $41, $0a
	.word @song0ref1602
	.byte $41, $0a
	.word @song0ref1602
@song0ref1799:
	.byte $85, $00, $81, $80, $1b, $00, $87, $86, $22, $85, $00, $81, $80, $1b
	.byte $41, $11
	.word @song0ref1760
	.byte $41, $63
	.word @song0ref1601
	.byte $41, $59
	.word @song0ref1601
	.byte $41, $0c
	.word @song0ref1724
	.byte $41, $63
	.word @song0ref1600
	.byte $41, $38
	.word @song0ref1601
	.byte $41, $0a
	.word @song0ref1602
	.byte $41, $0a
	.word @song0ref1602
	.byte $41, $0b
	.word @song0ref1799
	.byte $41, $11
	.word @song0ref1760
	.byte $41, $63
	.word @song0ref1601
	.byte $41, $2e
	.word @song0ref1601
	.byte $41, $0f
	.word @song0ref480
	.byte $41, $0e
	.word @song0ref481
	.byte $41, $0e
	.word @song0ref481
	.byte $41, $0e
	.word @song0ref481
	.byte $bf, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $0f
	.word @song0ref480
	.byte $41, $0e
	.word @song0ref481
	.byte $41, $0e
	.word @song0ref481
	.byte $41, $0e
	.word @song0ref481
	.byte $41, $0e
	.word @song0ref481
	.byte $41, $0e
	.word @song0ref481
	.byte $41, $0e
	.word @song0ref481
	.byte $41, $0e
	.word @song0ref481
	.byte $41, $0e
	.word @song0ref481
	.byte $bf, $42
	.word @song0ch4loop
